const languages = {
  abap: { label: "ABAP" },
  actionscript: { label: "ActionScript" },
  ada: { label: "ADA" },
  apacheconf: { label: "Apache Conf", ace: "apache_conf" },
  autohotkey: { label: "AutoHotkey / AutoIt" },
  aql: { label: "AQL" },
  batchfile: { label: "BatchFile", ace: "batch" },
  bro: { label: "Bro" },
  c: { label: "C", ace: "c_cpp" },
  cpp: { label: "C++", ace: "c_cpp" },
  clike: { label: "C-Like", ace: "c_cpp" },
  crystal: { label: "Crystal" },
  clojure: { label: "Clojure" },
  coffee: { label: "CoffeeScript" },
  csharp: { label: "C#" },
  css: { label: "CSS" },
  d: { label: "D" },
  dart: { label: "Dart" },
  diff: { label: "Diff" },
  dockerfile: { label: "Dockerfile" },
  eiffel: { label: "Eiffel" },
  ejs: { label: "EJS" },
  elixir: { label: "Elixir" },
  elm: { label: "Elm" },
  erlang: { label: "Erlang" },
  fortran: { label: "Fortran" },
  fsharp: { label: "FSharp" },
  gcode: { label: "Gcode" },
  gherkin: { label: "Gherkin" },
  git: { label: "Gitignore", ace: "gitignore" },
  glsl: { label: "Glsl" },
  go: { label: "Go", ace: "golang" },
  graphql: { label: "GraphQLSchema", ace: "graphqlschema" },
  groovy: { label: "Groovy" },
  haml: { label: "HAML" },
  handlebars: { label: "Handlebars" },
  haskell: { label: "Haskell" },
  haxe: { label: "haXe" },
  html: { label: "HTML" },
  ini: { label: "INI" },
  io: { label: "Io" },
  java: { label: "Java" },
  javascript: { label: "JavaScript" },
  json: { label: "JSON" },
  jsx: { label: "JSX" },
  julia: { label: "Julia" },
  kotlin: { label: "Kotlin" },
  latex: { label: "LaTeX" },
  less: { label: "LESS" },
  liquid: { label: "Liquid" },
  lisp: { label: "Lisp" },
  livescript: { label: "LiveScript" },
  lua: { label: "Lua" },
  makefile: { label: "Makefile" },
  markdown: { label: "Markdown" },
  matlab: { label: "MATLAB" },
  mel: { label: "MEL" },
  mixal: { label: "MIXAL" },
  nginx: { label: "Nginx" },
  nix: { label: "Nix" },
  nim: { label: "Nim" },
  nsis: { label: "NSIS" },
  objectivec: { label: "Objective-C" },
  ocaml: { label: "OCaml" },
  pascal: { label: "Pascal" },
  perl: { label: "Perl" },
  php: { label: "PHP" },
  powershell: { label: "Powershell" },
  prolog: { label: "Prolog" },
  properties: { label: "Properties" },
  protobuf: { label: "Protobuf" },
  python: { label: "Python" },
  r: { label: "R" },
  ruby: { label: "Ruby" },
  rust: { label: "Rust" },
  sass: { label: "SASS" },
  scala: { label: "Scala" },
  scheme: { label: "Scheme" },
  scss: { label: "SCSS" },
  sh: { label: "SH" },
  smarty: { label: "Smarty" },
  sql: { label: "SQL" },
  stylus: { label: "Stylus" },
  svg: { label: "SVG" },
  swift: { label: "Swift" },
  tcl: { label: "Tcl" },
  terraform: { label: "Terraform" },
  text: { label: "Text" },
  textile: { label: "Textile" },
  toml: { label: "Toml" },
  tsx: { label: "TSX" },
  twig: { label: "Twig" },
  typescript: { label: "Typescript" },
  vala: { label: "Vala" },
  vb: { label: "VBScript", ace: "vbscript" },
  velocity: { label: "Velocity" },
  verilog: { label: "Verilog" },
  vhdl: { label: "VHDL" },
  xml: { label: "XML" },
  xquery: { label: "XQuery" },
  yaml: { label: "YAML" },
  django: { label: "Django" },
  bash: { label: "Bash / Shell", ace: "text" }
};

export default languages;

export function convertToAce(lang: string) {
  // @ts-ignore
  if (languages[lang]) {
    // @ts-ignore
    if (languages[lang].ace) {
      // @ts-ignore
      return languages[lang].ace;
    }
    return lang;
  }
  return "markup";
}
